spring:
    application:
        name: spring-boot-redis-integration-service

    profiles:
        active: ${SPRING_PROFILES_ACTIVE:local} # default profile fallback

    main:
        banner-mode: off
    banner:
        location: classpath:banner.txt

    security:
        user:
            name: ${SPRING_SECURITY_USER:admin}
            password: ${SPRING_SECURITY_PASSWORD:admin}
            roles: ACTUATOR_ADMIN

    data:
        redis:
            host: ${REDIS_HOST:localhost}
            port: ${REDIS_PORT:6379}
            username: ${REDIS_USERNAME:}
            password: ${REDIS_PASSWORD:}
            timeout: ${REDIS_TIMEOUT:60000}
            # Lettuce connection pool configuration
            lettuce:
                pool:
                    max-active: 20
                    max-idle: 10
                    min-idle: 2
                    max-wait: 1000ms

    redis:
        # Optional serialization configuration
        serializer:
            key: STRING
            value: JSON

server:
    port: ${SERVER_PORT:8080}
    servlet:
        context-path: /
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,application/json,application/xml,text/css,text/javascript,application/javascript
        min-response-size: 1024

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,loggers,env,threaddump,beans,configprops # tighten for security in prod
    endpoint:
        health:
            show-details: when_authorized
    health:
        redis:
            enabled: true

audit:
    connector:
        url: ${AUDIT_CONNECTOR_URL:http://localhost:8085/audit}
        username: ${AUDIT_CONNECTOR_USER:audit}
        password: ${AUDIT_CONNECTOR_PASSWORD:audit}

logging:
    level:
        root: INFO
        com.sid: INFO
        org.springframework.data.redis: DEBUG
        io.lettuce.core: INFO
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %level [%thread] %logger{36} - %msg%n"
